# Generated by Django 6.0.6 on 2026-07-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='pontos_recuperados_desde_ultimo_exercicio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultima_recuperacao_pontos_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
