# Generated by Django 6.0.6 on 2026-08-17 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('reason', models.TextField(blank=True, max_length=1000)),
                ('confirmation_token_hash', models.CharField(max_length=64)),
                ('confirmation_expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('awaiting_confirmation', 'Aguardando confirmação'), ('confirmed', 'Confirmada'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], db_index=True, default='awaiting_confirmation', max_length=30)),
            ],
            options={
                'verbose_name': 'Solicitação de exclusão de conta',
                'verbose_name_plural': 'Solicitações de exclusão de conta',
                'ordering': ['-created_at'],
            },
        ),
    ]
