# Generated by Django 6.0.6 on 2026-06-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome da Categoria'),
        ),
    ]
