# Generated by Django 6.0.6 on 2026-07-02 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('multiple_choice_translation', 'Multipla escolha'), ('write_translation_from_text_audio', 'Escrever com texto e audio'), ('write_translation_from_audio', 'Escrever ouvindo audio'), ('speak_written_text', 'Falar texto escrito')], max_length=50)),
                ('prompt', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=list)),
                ('answer_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='cards.card')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
