# Generated by Django 6.0.6 on 2026-07-02 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExerciseSet', '0001_initial'),
        ('exercicio', '0002_alter_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='ExerciseSet.exerciseset', verbose_name='Conjunto de exercicios'),
        ),
    ]
