# Generated by Django 6.0.6 on 2026-07-02 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExerciseSet', '0002_exercisesetprogress'),
        ('exercicio', '0003_exercise_exercise_set'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_correct', models.BooleanField(default=True)),
                ('answer', models.JSONField(blank=True, default=dict)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercicio.exercise')),
                ('exercise_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExerciseSet.exerciseset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
