# Generated by Django 6.0.6 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_usercardaccess'),
        ('exercicio', '0005_alter_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='pair_cards',
            field=models.ManyToManyField(
                blank=True,
                related_name='matching_exercises',
                to='cards.card',
                verbose_name='Cards para associacao',
            ),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(
                choices=[
                    ('multiple_choice_translation', 'Multipla escolha'),
                    ('multiple_choice_audio_english', 'Multipla escolha com audio em ingles'),
                    ('write_translation_from_text_audio', 'Escrever com texto e audio'),
                    ('write_translation_from_audio', 'Escrever ouvindo audio'),
                    ('speak_written_text', 'Falar texto escrito'),
                    ('just_audio', 'Apenas audio'),
                    ('matching_pairs', 'Associar traducao e ingles'),
                ],
                max_length=50,
            ),
        ),
    ]
