# Generated by Django 6.0.6 on 2026-07-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='cards/audios/', verbose_name='Áudio'),
        ),
    ]
