# Generated by Django 6.0.6 on 2026-07-13 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCardAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='cards.card', verbose_name='Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Primeiro acesso ao card',
                'verbose_name_plural': 'Primeiros acessos aos cards',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'card'), name='unique_user_card_access')],
            },
        ),
    ]
