# Generated by Django 6.0.6 on 2026-07-02 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subniveis', '0003_alter_subnivel_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sublevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='subniveis.subnivel', verbose_name='Subnivel')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
