# Generated by Django 6.0.6 on 2026-06-26 19:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubNivel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('subnivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subniveis', to='niveis.nivel', verbose_name='Nível')),
            ],
            options={
                'verbose_name': 'Subnível',
                'verbose_name_plural': 'Subníveis',
                'ordering': ['nome'],
            },
        ),
    ]
