# Generated by Django 6.0.6 on 2026-06-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subniveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subnivel',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Subnível', 'verbose_name_plural': 'Subníveis'},
        ),
        migrations.AddField(
            model_name='subnivel',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
