# Generated by Django 6.0.6 on 2026-06-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subniveis', '0002_alter_subnivel_options_subnivel_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnivel',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
